// Which pre-rendered /portal/<stopId>-<era>.jpg fallback images actually exist.
// Generated by scratchpad/pregen.py against the live OpenAI render, so the camera
// flow can serve a real period photo instantly when the live render is slow/down
// — and skip the network request entirely when no file exists (no 404 noise).
export const PORTAL_ASSETS = new Set<string>([
  "gillett-square-bollard-1890s",
  "gillett-square-bollard-1943",
  "gillett-square-bollard-1974",
  "gillett-square-bollard-2050",
  "kingsland-postbox-1890s",
  "kingsland-postbox-1943",
  "kingsland-postbox-1974",
  "kingsland-postbox-2050",
  "ridley-road-market-1890s",
  "ridley-road-market-1943",
  "ridley-road-market-1974",
  "ridley-road-market-2050",
  "ashwin-street-bollard-1890s",
  "ashwin-street-bollard-1943",
  "ashwin-street-bollard-1974",
  "ashwin-street-bollard-2050",
  // Dalston Kingsland station — the venue landmark. Wired as the universal
  // fallback in cachedRenderFor for any stop without an authored render
  // (stops 5–6 / GPS mismatch), so every snap reveals instantly.
  "dalston-station-1890s",
  "dalston-station-1943",
  "dalston-station-1974",
  "dalston-station-2050",
]);
